call by command word as well as by symlink or sourcing

diff --git a/irqfunctions b/irqfunctions
--- a/irqfunctions
+++ b/irqfunctions
@@ -126,7 +126,6 @@ printInterestingNetworkInterrupts() {
         local_affinity_bitmask_reversed=$(reversedBitmaskFromHexmask $local_affinity_hexmask)
         local_cpu_list=$(cat $device_dir/local_cpulist)
         numa_node=$(cat $device_dir/numa_node)
-
         echo "$interface $businfo has numa node $numa_node and local affinity $local_affinity_hexmask $local_affinity_bitmask_reversed $local_cpu_list"
         echo "--------------"
 
@@ -147,5 +146,19 @@ printInterestingNetworkInterrupts() {
 
 # if called via symlink, call function corresponding to the link name.
 if [ -L $0 ]; then
-	"$(basename $0)" $@
+    "$(basename $0)" $@
+    exit 0
 fi
+
+cmd=$1
+shift
+case "$cmd" in
+    print) printInterestingNetworkInterrupts ;;
+    hex2list) cpuListFromHexmask $@ ;;
+    hex2bin) reversedBitmaskFromHexmask $@ ;;
+    bin2hex) hexmaskFromReversedBitmask $@ ;;
+    bin2list) cpuListFromReversedBitmask $@ ;;
+    list2hex) hexmaskFromCpuList $@ ;;
+    list2bin) reversedBitmaskFromCpuList $@ ;;
+    *) echo "can't understand $1, try one of [print, hex2list, hex2bin, bin2list, bin2hex, list2hex, list2bin]"; exit 1;;
+esac
